`timescale 1ns/1ps
module tb_spi_handshake_top;

    parameter DATA_WIDTH = 8;
    
    // Master fast base clock definition (e.g., 50MHz = 20ns period)
    parameter FAST_CLK_PERIOD = 20; 
    
    // How many fast clock cycles equal ONE slow system clock cycle?
    // Example: System clock is 5x slower than the fast clock base.
    localparam int FAST_CYCLES_PER_SYSTEM_CLK = 5;

    // DUT Inputs
    reg clk;             // Slow system clock generated by the TB
    reg spi_clk;         // Fast SPI clock driven by the task
    reg spi_data;
    reg spi_cs;
    reg system_ready;

    // DUT Outputs
    wire data_valid;
    wire [DATA_WIDTH-1:0] data_out;

    // Internal Master Base Clock (Verilator's evaluation engine heart)
    reg fast_base_clk;

    // Queues
    reg [DATA_WIDTH-1:0] tx_fifo [$];
    reg [DATA_WIDTH-1:0] rx_fifo [$];
    reg [DATA_WIDTH-1:0] expected_data, actual_data;

    // Instantiate DUT
    spi_top_wrap #(.DATA_WIDTH(DATA_WIDTH)) uut (
        .spi_clk(spi_clk),
        .spi_data(spi_data),
        .spi_cs(spi_cs),
        .clk(clk),
        .system_ready(system_ready),
        .data_valid(data_valid),
        .data_out(data_out)
    );

    // 1. Generate the Master FAST Base Clock
    initial begin
        fast_base_clk = 0;
        forever #(FAST_CLK_PERIOD/2) fast_base_clk = ~fast_base_clk;
    end

    // 2. Generate the SLOW System Clock synchronously from the fast clock
    // This guarantees both clocks are perfectly aligned at time 0 and never drift.
    initial begin
        clk = 0;
        forever begin
            repeat(FAST_CYCLES_PER_SYSTEM_CLK) @(negedge fast_base_clk);
            clk = ~clk;
        end
    end

    // 3. Receiver Block (Synchronized safely to the SLOW clock's negative edge)
    initial begin
        system_ready = 0;
        repeat(5) @(negedge clk);

        forever begin
            repeat($urandom_range(0, 5)) begin
                system_ready <= 1'b0;
                @(negedge clk);
            end
            
            system_ready <= 1'b1;
            while (!data_valid) begin
                @(negedge clk);
            end

            $display("[%0t] Rx data caught = %0x", $time, data_out);
            rx_fifo.push_back(data_out);
            
            @(negedge clk);
        end
    end

    // 4. Checker Block (Runs on the master clock to avoid delays)
    initial begin
        forever begin
            @(negedge fast_base_clk);
            if (tx_fifo.size() > 0 && rx_fifo.size() > 0) begin
                expected_data = tx_fifo.pop_front();
                actual_data = rx_fifo.pop_front();
                
                if (actual_data !== expected_data) begin
                    $display("[%0t] ERROR: Mismatch! Got %h, Expected %h", $time, actual_data, expected_data);
                end else begin
                    $display("[%0t] SUCCESS: Data %h received correctly.", $time, actual_data);
                end
            end
        end
    end

    // 5. Main Stimulus Sequence
    initial begin
        spi_clk      <= 1'b0;
        spi_data     <= 1'b0;
        spi_cs       <= 1'b1;
        
        repeat(5) @(negedge clk); // Settle using slow clock
        
        repeat(10) begin
            send_spi_byte($urandom()[7:0]); 
            repeat(5) @(negedge clk);
        end
        
        repeat(50) @(negedge clk);
        $display("[%0t] All tests completed.", $time);
        $finish;
    end

    // 6. Fast Driver Task: Drives SPI at the speed of the fast base clock
    task send_spi_byte(input [DATA_WIDTH-1:0] data);
        reg [DATA_WIDTH-1:0] temp_data;
        begin
            temp_data = data;
            $display("[%0t] Sending FAST SPI Byte: %0x", $time, temp_data);
            tx_fifo.push_back(temp_data);
            
            spi_cs <= 1'b0;
            
            repeat(DATA_WIDTH) begin
                // Target the negative edge of the fast clock to change data
                spi_data <= temp_data[DATA_WIDTH-1];
                temp_data = temp_data << 1;
                
                // SPI Clock High lasts for 1 fast clock cycle
                @(negedge fast_base_clk);
                spi_clk <= 1'b1; 
                
                // SPI Clock Low lasts for 1 fast clock cycle
                @(negedge fast_base_clk);
                spi_clk <= 1'b0; 
            end
            
            @(negedge fast_base_clk);
            spi_cs  <= 1'b1;
            spi_clk <= 1'b0;
        end
    endtask

endmodule
