// Auto-generated by scripts/gen_rtl_weights.py -- do not edit.
// hidden layer biases, Q11.21 in 32-bit two's complement.

`ifndef HIDDEN_BIASES_SVH_
`define HIDDEN_BIASES_SVH_

localparam HIDDEN_BIAS_WIDTH = 32;
localparam HIDDEN_BIAS_ROWS  = 16;
localparam HIDDEN_BIAS_COLS  = 1;

localparam signed [31:0] BIAS_HIDDEN_0_0 = -32'sd129285;
localparam signed [31:0] BIAS_HIDDEN_1_0 = 32'sd480519;
localparam signed [31:0] BIAS_HIDDEN_2_0 = 32'sd1313119;
localparam signed [31:0] BIAS_HIDDEN_3_0 = 32'sd469482;
localparam signed [31:0] BIAS_HIDDEN_4_0 = 32'sd395179;
localparam signed [31:0] BIAS_HIDDEN_5_0 = 32'sd797895;
localparam signed [31:0] BIAS_HIDDEN_6_0 = -32'sd829571;
localparam signed [31:0] BIAS_HIDDEN_7_0 = -32'sd132239;
localparam signed [31:0] BIAS_HIDDEN_8_0 = 32'sd115065;
localparam signed [31:0] BIAS_HIDDEN_9_0 = -32'sd593383;
localparam signed [31:0] BIAS_HIDDEN_10_0 = 32'sd26841;
localparam signed [31:0] BIAS_HIDDEN_11_0 = -32'sd1309948;
localparam signed [31:0] BIAS_HIDDEN_12_0 = 32'sd1227427;
localparam signed [31:0] BIAS_HIDDEN_13_0 = -32'sd869844;
localparam signed [31:0] BIAS_HIDDEN_14_0 = -32'sd479375;
localparam signed [31:0] BIAS_HIDDEN_15_0 = 32'sd1592939;

// Indexable form for generate loops: BIAS_HIDDEN[row][col].
// NOTE: assignment patterns fill a PACKED array from the high index down,
// so rows/cols are listed in descending order. Entries are the named
// localparams above so the reversal stays self-checking.
localparam logic signed [HIDDEN_BIAS_ROWS-1:0][HIDDEN_BIAS_COLS-1:0][HIDDEN_BIAS_WIDTH-1:0] BIAS_HIDDEN = '{
    '{BIAS_HIDDEN_15_0},   // row 15
    '{BIAS_HIDDEN_14_0},   // row 14
    '{BIAS_HIDDEN_13_0},   // row 13
    '{BIAS_HIDDEN_12_0},   // row 12
    '{BIAS_HIDDEN_11_0},   // row 11
    '{BIAS_HIDDEN_10_0},   // row 10
    '{BIAS_HIDDEN_9_0},   // row 9
    '{BIAS_HIDDEN_8_0},   // row 8
    '{BIAS_HIDDEN_7_0},   // row 7
    '{BIAS_HIDDEN_6_0},   // row 6
    '{BIAS_HIDDEN_5_0},   // row 5
    '{BIAS_HIDDEN_4_0},   // row 4
    '{BIAS_HIDDEN_3_0},   // row 3
    '{BIAS_HIDDEN_2_0},   // row 2
    '{BIAS_HIDDEN_1_0},   // row 1
    '{BIAS_HIDDEN_0_0}   // row 0
};

`endif // HIDDEN_BIASES_SVH_
