// Auto-generated by scripts/gen_rtl_weights.py -- do not edit.
// output layer biases, Q11.21 in 32-bit two's complement.

`ifndef OUTPUT_BIASES_SVH_
`define OUTPUT_BIASES_SVH_

localparam OUTPUT_BIAS_WIDTH = 32;
localparam OUTPUT_BIAS_ROWS  = 10;
localparam OUTPUT_BIAS_COLS  = 1;

localparam signed [31:0] BIAS_OUTPUT_0_0 = -32'sd985082;
localparam signed [31:0] BIAS_OUTPUT_1_0 = 32'sd1255915;
localparam signed [31:0] BIAS_OUTPUT_2_0 = -32'sd779720;
localparam signed [31:0] BIAS_OUTPUT_3_0 = -32'sd387347;
localparam signed [31:0] BIAS_OUTPUT_4_0 = 32'sd497457;
localparam signed [31:0] BIAS_OUTPUT_5_0 = 32'sd1215094;
localparam signed [31:0] BIAS_OUTPUT_6_0 = -32'sd46496;
localparam signed [31:0] BIAS_OUTPUT_7_0 = 32'sd673887;
localparam signed [31:0] BIAS_OUTPUT_8_0 = -32'sd1183124;
localparam signed [31:0] BIAS_OUTPUT_9_0 = 32'sd205973;

// Indexable form for generate loops: BIAS_OUTPUT[row][col].
// NOTE: assignment patterns fill a PACKED array from the high index down,
// so rows/cols are listed in descending order. Entries are the named
// localparams above so the reversal stays self-checking.
localparam logic signed [OUTPUT_BIAS_ROWS-1:0][OUTPUT_BIAS_COLS-1:0][OUTPUT_BIAS_WIDTH-1:0] BIAS_OUTPUT = '{
    '{BIAS_OUTPUT_9_0},   // row 9
    '{BIAS_OUTPUT_8_0},   // row 8
    '{BIAS_OUTPUT_7_0},   // row 7
    '{BIAS_OUTPUT_6_0},   // row 6
    '{BIAS_OUTPUT_5_0},   // row 5
    '{BIAS_OUTPUT_4_0},   // row 4
    '{BIAS_OUTPUT_3_0},   // row 3
    '{BIAS_OUTPUT_2_0},   // row 2
    '{BIAS_OUTPUT_1_0},   // row 1
    '{BIAS_OUTPUT_0_0}   // row 0
};

`endif // OUTPUT_BIASES_SVH_
