"""Turn the quantized weight dumps into the files the RTL preloads.

Run it:  python3 scripts/gen_rtl_weights.py

Reads scripts/quantized_weights/*.txt (quantizer.py output: integer rows plus a
header naming the scale) and writes fpga_files/rtl/weights/:

    hidden_0..15.hex    one file per hidden neuron, 784 words -- hidden weight BRAM
    output_0..9.hex     one file per output neuron, 16 words  -- output weight BRAM
    hidden_biases.svh   `include`d by pipe_top.sv, feeds MAC_BIAS
    output_biases.svh   same, output layer

Re-run after every quantizer.py run. Widths below must match pipe_params.sv.
"""

import math
import os

# --- word widths, keep in step with rtl/compute/pipe_params.sv -------------
WEIGHT_WIDTH = 16   # HIDDEN_WEIGHT_WIDTH / OUTPUT_WEIGHT_WIDTH
BIAS_WIDTH   = 32   # HIDDEN_ACCUM_WIDTH / OUTPUT_ACCUM_WIDTH (biases preload the accumulator)
# --------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
IN_DIR = os.path.join(SCRIPT_DIR, "quantized_weights")
OUT_DIR = os.path.join(SCRIPT_DIR, os.pardir, "fpga_files", "rtl", "weights")


def read_quantized(name):
    """Integer rows from a quantizer.py file, with the scale from its header."""
    scale, rows = None, []
    with open(os.path.join(IN_DIR, name)) as f:
        for line in f:
            if line.startswith("#"):
                if line.startswith("# format"):
                    scale = int(line.split("scale")[1].split()[0])
            elif line.strip():
                rows.append([int(v) for v in line.split()])
    return rows, scale


def check_fits(vals, width, what):
    lo, hi = -(1 << (width - 1)), (1 << (width - 1)) - 1
    for v in vals:
        if not lo <= v <= hi:
            raise SystemExit("error: %s value %d does not fit signed %d bits"
                             % (what, v, width))


def q_format(width, scale):
    """"Q<int+sign>.<frac>" for a power-of-two scale, else the raw scale."""
    frac = int(round(math.log2(scale)))
    if 1 << frac != scale:
        return "scale %d" % scale
    return "Q%d.%d" % (width - frac, frac)


def write_hex(prefix, rows, width):
    """One .hex per row, one zero-padded word per line -- $readmemh format."""
    nibbles = (width + 3) // 4
    mask = (1 << width) - 1
    for i, row in enumerate(rows):
        check_fits(row, width, "%s_%d" % (prefix, i))
        path = os.path.join(OUT_DIR, "%s_%d.hex" % (prefix, i))
        with open(path, 'w') as f:
            for v in row:
                f.write("%0*x\n" % (nibbles, v & mask))
    print("Wrote: %s_0..%d.hex (%d words each)" % (prefix, len(rows) - 1, len(rows[0])))


def sv_literal(v, width):
    return "%s%d'sd%d" % ("-" if v < 0 else "", width, abs(v))


def write_biases(layer, vals, width, scale):
    """The `include`d localparam file: named entries plus a packed 2-D array."""
    check_fits(vals, width, "%s bias" % layer)
    upper = layer.upper()
    guard = "%s_BIASES_SVH_" % upper
    path = os.path.join(OUT_DIR, "%s_biases.svh" % layer)

    with open(path, 'w') as f:
        f.write("// Auto-generated by scripts/gen_rtl_weights.py -- do not edit.\n")
        f.write("// %s layer biases, %s in %d-bit two's complement.\n\n"
                % (layer, q_format(width, scale), width))
        f.write("`ifndef %s\n`define %s\n\n" % (guard, guard))
        f.write("localparam %s_BIAS_WIDTH = %d;\n" % (upper, width))
        f.write("localparam %s_BIAS_ROWS  = %d;\n" % (upper, len(vals)))
        f.write("localparam %s_BIAS_COLS  = 1;\n\n" % upper)

        for row, v in enumerate(vals):
            f.write("localparam signed [%d:0] BIAS_%s_%d_0 = %s;\n"
                    % (width - 1, upper, row, sv_literal(v, width)))

        f.write("\n// Indexable form for generate loops: BIAS_%s[row][col].\n" % upper)
        f.write("// NOTE: assignment patterns fill a PACKED array from the high index down,\n")
        f.write("// so rows/cols are listed in descending order. Entries are the named\n")
        f.write("// localparams above so the reversal stays self-checking.\n")
        f.write("localparam logic signed [%s_BIAS_ROWS-1:0][%s_BIAS_COLS-1:0]"
                "[%s_BIAS_WIDTH-1:0] BIAS_%s = '{\n" % (upper, upper, upper, upper))
        rows = list(reversed(range(len(vals))))
        for row in rows:
            comma = "" if row == rows[-1] else ","
            f.write("    '{BIAS_%s_%d_0}%s   // row %d\n" % (upper, row, comma, row))
        f.write("};\n\n`endif // %s\n" % guard)

    print("Wrote: %s_biases.svh (%d rows, %s)"
          % (layer, len(vals), q_format(width, scale)))


if __name__ == "__main__":
    for layer in ("hidden", "output"):
        weights, w_scale = read_quantized("%s_weights.txt" % layer)
        biases, b_scale = read_quantized("%s_biases.txt" % layer)

        write_hex(layer, weights, WEIGHT_WIDTH)
        write_biases(layer, biases[0], BIAS_WIDTH, b_scale)
        print("  weights %s, biases %s\n"
              % (q_format(WEIGHT_WIDTH, w_scale), q_format(BIAS_WIDTH, b_scale)))

    print("Done. Re-run scripts/gen_matmul_golden.py if it is still in use.")
