#!/usr/bin/env python3
"""Generate the expected product for tb_matrix_mult_top.

    A (MxK) hidden weights  *  B (KxN) pixels  =  C (MxN) activations

The operands are not driven by the testbench - each single_port_bram inside
matrix_mult_top preloads itself from rtl/weights/<prefix>_<i>.hex - so the
golden answer is computed from those same files.

Mirrors the RTL: $readmemh keeps the low DATA_WIDTH bits, bram_wrapper
zero-extends to the common compute width (SIGN_EXTEND=0 on both edges), and
systolic_mac does a signed multiply-accumulate wrapped to ACC_WIDTH.

Writes a flat $readmemh file, row-major, that tb_matrix_mult.v compares against
c. Re-run whenever the weights, the pixels, or the settings below change.
"""

import os

# --- keep in step with tb_matrix_mult.v / matrix_mult_top.sv ---------------
WEIGHTS_DIR  = "fpga_files/rtl/weights"
A_PREFIX     = "hidden"   # M edge: one file per row of A
B_PREFIX     = "pixels"   # N edge: one file per column of B
OUT_FILE     = "fpga_files/tb/matrix_mult/expected_c.hex"

M, K, N      = 16, 784, 1
A_DATA_WIDTH = 16         # signed Q8.8 weights, needs all 16 bits
B_DATA_WIDTH = 8          # unsigned pixel bytes
ACC_WIDTH    = 32
# --------------------------------------------------------------------------

COMPUTE_WIDTH = max(A_DATA_WIDTH, B_DATA_WIDTH)


def load(prefix, idx, data_width):
    """Read one .hex the way the BRAM sees it, as COMPUTE_WIDTH signed ints."""
    path = os.path.join(WEIGHTS_DIR, "%s_%d.hex" % (prefix, idx))
    words = [ln.split("//")[0].strip() for ln in open(path)]
    vals = [int(w, 16) & ((1 << data_width) - 1) for w in words if w]

    if len(vals) < K:
        raise SystemExit("error: %s has %d entries, need %d" % (path, len(vals), K))
    vals = vals[:K]

    # zero-extended to COMPUTE_WIDTH, then read as signed by systolic_mac
    return [v - (1 << COMPUTE_WIDTH) if v >> (COMPUTE_WIDTH - 1) else v
            for v in vals]


a = [load(A_PREFIX, r, A_DATA_WIDTH) for r in range(M)]
b = [load(B_PREFIX, c, B_DATA_WIDTH) for c in range(N)]

# C[r][c] = sum_k A[r][k] * B[k][c]
c = [[sum(a[r][i] * b[col][i] for i in range(K)) for col in range(N)]
     for r in range(M)]

nibbles = (ACC_WIDTH + 3) // 4
os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
with open(OUT_FILE, "w") as fh:
    fh.write("// GENERATED by scripts/gen_matmul_golden.py - do not edit.\n")
    fh.write("// A (%dx%d) %s_*.hex @ %d bits * B (%dx%d) %s_*.hex @ %d bits\n"
             % (M, K, A_PREFIX, A_DATA_WIDTH, K, N, B_PREFIX, B_DATA_WIDTH))
    fh.write("// signed MAC at %d bits, wrapped to ACC_WIDTH=%d\n"
             % (COMPUTE_WIDTH, ACC_WIDTH))
    for r in range(M):
        for col in range(N):
            fh.write("%0*X   // C[%d][%d] = %d\n"
                     % (nibbles, c[r][col] & ((1 << ACC_WIDTH) - 1),
                        r, col, c[r][col]))

print("wrote %s (%d values)" % (OUT_FILE, M * N))

biggest = max(abs(c[r][col]) for r in range(M) for col in range(N))
limit = 1 << (ACC_WIDTH - 1)
if biggest >= limit:
    print("  WARNING: largest |sum| %d exceeds signed %d-bit range +/-%d; "
          "the RTL wraps and the golden file wraps with it"
          % (biggest, ACC_WIDTH, limit))
else:
    print("  largest |sum| %d fits the signed %d-bit accumulator (+/-%d)"
          % (biggest, ACC_WIDTH, limit))
