"""Integer model of the FPGA inference pipeline.

Reads pixels.txt (784 uint8 values, any whitespace layout) and runs the same
integer arithmetic as pipe_top: hidden matmul -> ReLU -> requantize -> output
matmul -> argmax. Writes relu.hex, output.hex and argmax.hex next to this file.

Regenerate pixels.txt for a different MNIST test image by reading
data/MNIST/raw/t10k-images-idx3-ubyte at offset 16 + 784*index.
"""

import os
import numpy as np

DIR = os.path.dirname(os.path.abspath(__file__))
WEIGHT_DIR = os.path.join(DIR, os.pardir, "quantized_weights")

WEIGHT_SCALE = 8192       # Q3.13
PIXEL_SCALE = 256         # raw uint8, value = px / 256
PIXEL_MAX = 255           # largest uint8, not the scale -- bounds use this
ACC_SCALE = WEIGHT_SCALE * PIXEL_SCALE   # 2**21, Q11.21 in 32 bits
ACT_SCALE = 256           # Q8.8 requantized activation
SHIFT = 13                # 2**21 -> 2**8
ACC_WIDTH = 32
ACT_WIDTH = 16


def accumulator_bound(weights, biases, in_max):
    """(min, max) an accumulator can reach for any input in [0, in_max].

    Inputs are non-negative by construction -- uint8 pixels, post-ReLU
    activations -- so the extremes come from an input sitting at in_max
    wherever the weight has the wanted sign and 0 everywhere else. That is a
    real uint8 image, so the bound is tight, not just conservative.
    """
    lo = int((in_max * np.clip(weights, None, 0).sum(1) + biases).min())
    hi = int((in_max * np.clip(weights, 0, None).sum(1) + biases).max())
    return lo, hi


def check_bounds(wh, bh, wo, bo):
    """Assert no input image at all can overflow the widths RTL is built to.

    Sizing from the activations MNIST happens to produce is a statistical
    argument; these bounds hold for every possible input, so a retrain that
    outgrows a width fails here instead of silently wrapping in hardware.
    """
    h_lo, h_hi = accumulator_bound(wh, bh, PIXEL_MAX)
    act_max = max(h_hi, 0) >> SHIFT          # ReLU floors the low side at 0
    o_lo, o_hi = accumulator_bound(wo, bo, act_max)

    for what, vals, width in (("hidden accumulator", [h_lo, h_hi], ACC_WIDTH),
                              ("activation", [act_max], ACT_WIDTH),
                              ("logit accumulator", [o_lo, o_hi], ACC_WIDTH)):
        assert bits(vals) <= width, f"{what} needs {bits(vals)} bits, have {width}"
    return h_lo, h_hi, act_max, o_lo, o_hi


def read_quantized(name):
    """Integer rows from a quantizer.py file, with the scale from its header."""
    scale, rows = None, []
    with open(os.path.join(WEIGHT_DIR, name)) as f:
        for line in f:
            if line.startswith("#"):
                if line.startswith("# format"):
                    scale = int(line.split("scale")[1].split()[0])
            elif line.strip():
                rows.append([int(v) for v in line.split()])
    return np.array(rows, dtype=np.int64), scale


def read_pixels():
    with open(os.path.join(DIR, "pixels.txt")) as f:
        vals = [int(v) for line in f if not line.startswith("#")
                for v in line.split()]
    assert len(vals) == 784, f"expected 784 pixels, got {len(vals)}"
    return np.array(vals, dtype=np.int64)


def bits(vals):
    return max(int(abs(v)).bit_length() for v in np.ravel(vals)) + 1


def write_hex(name, vals, width, scale, what):
    nibbles = (width + 3) // 4
    entries = [f"{int(v) & ((1 << width) - 1):0{nibbles}x}" for v in vals]
    with open(os.path.join(DIR, name), 'w') as f:
        f.write("// GENERATED by scripts/model_pipeline/pipeline.py -- do not edit.\n")
        f.write(f"// {what}\n")
        if scale:
            f.write(f"// Integer scale factor: {scale} (real value = entry / {scale}).\n")
        f.write(f"// Width: {width} bits, two's complement.\n")
        for e in entries:
            f.write(e + "\n")


def load_weights():
    wh, s_hw = read_quantized("hidden_weights.txt")
    bh, s_hb = read_quantized("hidden_biases.txt")
    wo, s_ow = read_quantized("output_weights.txt")
    bo, s_ob = read_quantized("output_biases.txt")

    assert s_hw == s_ow == WEIGHT_SCALE, f"weights at {s_hw}/{s_ow}, expected {WEIGHT_SCALE}"
    assert s_hb == ACC_SCALE, f"hidden bias at {s_hb}, accumulator at {ACC_SCALE}"
    assert s_ob == ACC_SCALE, f"output bias at {s_ob}, accumulator at {ACC_SCALE}"

    check_bounds(wh, bh[0], wo, bo[0])
    return wh, bh[0], wo, bo[0]


def infer(px, weights):
    """Returns (relu, logits, predicted class), all integer."""
    wh, bh, wo, bo = weights
    hidden = wh @ px + bh
    relu = np.maximum(hidden, 0)
    act = relu >> SHIFT
    logits = wo @ act + bo

    assert bits(hidden) <= ACC_WIDTH, f"hidden accumulator needs {bits(hidden)} bits"
    assert bits(logits) <= ACC_WIDTH, f"logit accumulator needs {bits(logits)} bits"
    assert bits(act) <= ACT_WIDTH, f"activation needs {bits(act)} bits"

    return relu, logits, int(np.argmax(logits))


if __name__ == "__main__":
    weights = load_weights()
    relu, logits, pred = infer(read_pixels(), weights)

    write_hex("relu.hex", relu, ACC_WIDTH, ACC_SCALE, "ReLU output, 16 hidden neurons")
    write_hex("output.hex", logits, ACC_WIDTH, ACC_SCALE, "output layer logits, 10 classes")
    write_hex("argmax.hex", [pred], 4, None, "predicted class (signed compare)")

    h_lo, h_hi, act_max, o_lo, o_hi = check_bounds(*weights)
    print(f"worst case over every possible uint8 image:")
    print(f"  hidden accumulator [{h_lo:>11d}, {h_hi:>10d}]  {bits([h_lo, h_hi]):2d} / {ACC_WIDTH} bits")
    print(f"  activation         [{0:>11d}, {act_max:>10d}]  {bits([act_max]):2d} / {ACT_WIDTH} bits")
    print(f"  logit accumulator  [{o_lo:>11d}, {o_hi:>10d}]  {bits([o_lo, o_hi]):2d} / {ACC_WIDTH} bits")
    print(f"argmax {pred}")
